

```{r}

str_subset(string = colnames(dat_ques), pattern = "^visualTrap")



dat_ques$duration_seconds



dat_ques$visualTrap_Planets_correct


dat_ques[, str_subset(string = colnames(dat_ques), pattern = "^visualTrap_Planets")]
```


```{r}
dat_ques[, str_subset(string = colnames(dat_ques), pattern = "^visualTrap_Collision")]

```







# Summary tables

```{r}
#| label: summary-tables

paradata_column_summary <- dat_para_defocus %>%
  group_by(destination, field, output_field) %>%
  summarise(n_participants = dplyr::n_distinct(PROLIFIC_PID), .groups = "drop") %>%
  arrange(destination, field)

paradata_participant_summary <- dat_ques %>%
  select(PROLIFIC_PID, result_id, State, duration_seconds) %>%
  distinct() %>%
  left_join(dat_para_events %>% count(PROLIFIC_PID, name = "dat_para_defocus"), by = "PROLIFIC_PID") %>%
  left_join(paradata_defocus_long %>% count(PROLIFIC_PID, name = "defocus_event_rows"), by = "PROLIFIC_PID") %>%
  left_join(paradata_column_map %>% filter(destination == "wide") %>% count(PROLIFIC_PID, name = "paradata_wide_fields"), by = "PROLIFIC_PID") %>%
  left_join(paradata_column_map %>% filter(destination == "long") %>% count(PROLIFIC_PID, name = "paradata_long_fields"), by = "PROLIFIC_PID") %>%
  mutate(
    dat_para_defocus = tidyr::replace_na(dat_para_defocus, 0),
    defocus_event_rows = tidyr::replace_na(defocus_event_rows, 0),
    paradata_wide_fields = tidyr::replace_na(paradata_wide_fields, 0),
    paradata_long_fields = tidyr::replace_na(paradata_long_fields, 0)
  )

paradata_column_summary
paradata_participant_summary
```

# Summary statistics

```{r}
#| label: summary-statistics

summary_stats_df <- clean_complete %>%
  select(
    PROLIFIC_PID,
    duration_seconds,
    keyStats_count,
    keyStats_mean,
    keyStats_median,
    keyStats_min,
    keyStats_max
  ) %>%
  left_join(
    paradata_participant_summary %>%
      select(PROLIFIC_PID, dat_para_defocus, defocus_event_rows, paradata_wide_fields, paradata_long_fields),
    by = "PROLIFIC_PID"
  ) %>%
  mutate(
    dat_para_defocus = tidyr::replace_na(dat_para_defocus, 0),
    defocus_event_rows = tidyr::replace_na(defocus_event_rows, 0),
    paradata_wide_fields = tidyr::replace_na(paradata_wide_fields, 0),
    paradata_long_fields = tidyr::replace_na(paradata_long_fields, 0)
  )

psych::describe(summary_stats_df %>% select(where(is.numeric)))
```

## descriptive sample

```{r}
#| label: descriptive-sample

socidem_numeric <- socidem_df %>% select(where(is.numeric))

if (ncol(socidem_numeric) > 0) {
  psych::describe(socidem_numeric)
}

socidem_level_tables %>%
  filter(variable == "socidem_Sex")

socidem_level_tables %>%
  filter(variable == "socidem_Employment.status")
```

## descriptive mean differences

```{r}
#| label: summary-plots-anova

assoc_cols <- c("assoc1_valence", "assoc2_valence", "assoc3_valence", "assoc4_valence", "assoc5_valence")
attr_cols <- paste0("attributesFutureSociety-", 1:8)

clean_complete <- clean_complete %>%
  mutate(
    assoc_valence_mean = rowMeans(select(., all_of(assoc_cols)), na.rm = TRUE),
    attributes_mean = rowMeans(select(., all_of(attr_cols)), na.rm = TRUE)
  )

analysis_df <- clean_complete %>%
  select(PROLIFIC_PID, condition_FutureSociety, assoc_valence_mean, attributes_mean, all_of(attr_cols)) %>%
  drop_na(assoc_valence_mean, attributes_mean, condition_FutureSociety)

mean_summary <- analysis_df %>%
  pivot_longer(
    cols = c(assoc_valence_mean, attributes_mean),
    names_to = "measure",
    values_to = "value"
  ) %>%
  group_by(condition_FutureSociety, measure) %>%
  summarise(
    mean = mean(value, na.rm = TRUE),
    sd = sd(value, na.rm = TRUE),
    n = dplyr::n(),
    se = sd / sqrt(n),
    .groups = "drop"
  ) %>%
  mutate(
    measure = recode(
      measure,
      assoc_valence_mean = "Association Valence Mean",
      attributes_mean = "Attributes Mean"
    )
  )

ggplot(mean_summary, aes(x = condition_FutureSociety, y = mean, fill = measure)) +
  geom_col(position = position_dodge(width = 0.8), width = 0.7) +
  geom_errorbar(
    aes(ymin = mean - se, ymax = mean + se),
    position = position_dodge(width = 0.8),
    width = 0.2
  ) +
  labs(x = "Condition", y = "Mean", fill = "Measure") +
  theme_minimal()


anova_assoc <- afex::aov_ez(
  id = "PROLIFIC_PID",
  dv = "assoc_valence_mean",
  between = "condition_FutureSociety",
  data = analysis_df
)
anova_attr <- afex::aov_ez(
  id = "PROLIFIC_PID",
  dv = "attributes_mean",
  between = "condition_FutureSociety",
  data = analysis_df
)

summary(anova_assoc)
summary(anova_attr)
```


```{r}
attr_labels <- c(
  "1" = "Utopian",
  "2" = "Desirable",
  "3" = "Ideal",
  "4" = "Beneficial for the greater good",
  "5" = "Imaginative",
  "6" = "Innovative",
  "7" = "Creative",
  "8" = "Possible"
)

attr_long <- analysis_df %>%
  pivot_longer(
    cols = all_of(attr_cols),
    names_to = "item",
    values_to = "value"
  ) %>%
  mutate(
    item_num = stringr::str_extract(item, "[0-9]+"),
    item_label = recode(item_num, !!!attr_labels)
  )

attr_effects <- attr_long %>%
  filter(!is.na(value)) %>%
  group_by(item_label) %>%
  summarise(
    eta_sq = {
      fit <- aov(value ~ condition_FutureSociety)
      ss <- summary(fit)[[1]]
      ss_between <- ss["condition_FutureSociety", "Sum Sq"]
      ss_total <- sum(ss[, "Sum Sq"])
      if (is.na(ss_between) || is.na(ss_total) || ss_total == 0) NA_real_ else ss_between / ss_total
    },
    .groups = "drop"
  ) %>%
  mutate(
    eta_label = ifelse(is.na(eta_sq), "eta^2=NA", paste0("eta^2=", round(eta_sq, 2)))
  )

attr_effects_table <- attr_effects %>%
  arrange(desc(eta_sq))

attr_effects_table

item_order <- attr_effects %>%
  mutate(eta_order = ifelse(is.na(eta_sq), -Inf, eta_sq)) %>%
  arrange(desc(eta_order)) %>%
  pull(item_label)

label_order <- attr_effects %>%
  mutate(eta_order = ifelse(is.na(eta_sq), -Inf, eta_sq)) %>%
  arrange(desc(eta_order)) %>%
  mutate(facet_label = paste0(item_label, "\n", eta_label)) %>%
  pull(facet_label)

attr_summary <- attr_long %>%
  group_by(condition_FutureSociety, item_label) %>%
  summarise(
    mean = mean(value, na.rm = TRUE),
    sd = sd(value, na.rm = TRUE),
    n = dplyr::n(),
    se = sd / sqrt(n),
    .groups = "drop"
  ) %>%
  left_join(attr_effects %>% select(item_label, eta_label), by = "item_label") %>%
  mutate(
    item_label = factor(item_label, levels = item_order),
    facet_label = factor(paste0(item_label, "\n", eta_label), levels = label_order)
  )

condition_order <- analysis_df %>%
  distinct(condition_FutureSociety) %>%
  arrange(condition_FutureSociety) %>%
  pull(condition_FutureSociety)

attr_summary <- attr_summary %>%
  mutate(condition_FutureSociety = factor(condition_FutureSociety, levels = condition_order))

ggplot(attr_summary, aes(x = condition_FutureSociety, y = mean, fill = condition_FutureSociety)) +
  geom_col(width = 0.7) +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.2) +
  geom_text(aes(label = round(mean, 2)), vjust = -0.3, size = 3) +
  facet_wrap(~ facet_label, ncol = 4) +
  labs(x = "Condition", y = "Mean", fill = "Condition") +
  theme_minimal() +
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 30, hjust = 1))
```

```{r}
tmp <- clean_complete[, str_subset(string = colnames(clean_complete), pattern = "attri.*[1-9]")]
psych::corPlot(r = cor(tmp, use = "pairwise"))

hist(clean_complete$`attributesFutureSociety-8`)
hist(clean_complete$`attributesFutureSociety-4`)

tmp_efa <- psych::fa.parallel(x = tmp)
tmp_fa <- psych::fa(r = cor(tmp, use = "pairwise"), nfactors = 2, n.obs = nrow(tmp))
tmp_fa
```
